apiVersion: batch/v1
kind: CronJob
metadata:
  name: server-health-monitor
spec:
  schedule: "*/5 * * * *"   # every 5 minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: server-health-monitor
              image: pikachu003/server-health-monitor:latest
              imagePullPolicy: Always
              env:
                - name: SLACK_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: slack-webhook-secret
                      key: webhook-url
          restartPolicy: OnFailure
